### PR TITLE
Update cli.rb

### PR DESCRIPTION
**Pull request by keab42**

### CODE REVIEW

**Comment by keab42** [comment]
Sorry. Fixing a typo and my dodgy assumptions about adding numbers into strings.

**Comment by BenjaminBriggs** [comment]
Try installing it locally with $sudo gem install rake

-- 
Ben
Sent with Airmail

On 2 February 2016 at 10:51:23, Matthew Keable (notifications@github.com) wrote:

Sorry. Fixing a typo and my dodgy assumptions about adding numbers into strings.

**Comment by keab42** [comment]
Thanks.

**Comment by keab42** [comment]
I'll close this for now until I'm satisfied it works properly. Sorry to have been bothering you.

**Comment by BenjaminBriggs** [comment]
no problem. make a new request when you've got it working

**Pull request closed without merging**
